# Hardware{#hardware}

This page describes how to build the two main components of the hardware:
the *Sticky Pi Device* and the *Data Harvester*.
Briefly, multiple Sticky Pis are deployed in the field. Each device stores its images on its own SD card.
On a regular basis (*e.g.* weekly), experimenters use a data harvester to retrieve the data from multiple devices.
Silently, the data harvester also syncs the location and time of the devices it communicates with.
One Data Harvester may be used to maintain multiple traps. Multiple Data Harvesters can exist in the same platform (*e.g.* five experimenters, one harvester per experimenter, ten devices per experimenter).


This section involve familiarity with 3D printing, electronics, DIY, ...
We are working on streamlining the assembly process towards a more `off-the-shelf tool', but are generally happy to collaborate and help building devices -- do not hesitate to [contact us](/community#contact).

```{=html}
<!--
<style>
#doc-graph {
    height: 100%;
    width: 100%;
}
</style>
-->
<div class="container-fluid">
  <div class="row">
    <div id="doc-graph" class="col-lg-6 min-vh-100"></div>
    <div id="doc-info" class="col-lg-6"></div>
  </div>
</div>
```
