# Issues and community {#community -}

## Citation{-}

Sticky Pis are a research tool. As such, they are -- and will always be -- as free and open-source as possible. 
**If you use Sticky Pis as part of your research, please cite [our reference publication](`r PUBLICATION_URL`).**

## Having troubles{-}

If you are having issues or you want help with something, the best thing you can do is **fill an "issue" on the github repository** of the relevant tool.

## Contributing {-}

We welcome external contributions and hope Sticky Pis develops as part of a computational entomology community.

There are several ways you can contribute:

* By requesting features and reporting bugs through the github issue system
* By sending pull requests to preexisting tools
* By volunteering to maintain/develop a tools

## Contact {-}

Sticky Pis are developed at the [Plant-Insect Ecology and Evolution lab] at UBC, Vancouver(https://lfs-carrillo.sites.olt.ubc.ca/) in collaboration with the [Haney Lab](https://haneylab.msl.ubc.ca/) and the [Insect Biocontrol lab](https://profils-profiles.science.gc.ca/en/profile/paul-k-abram-phd). Do not hesitate to contact [Quentin Geissmann](qgeissmann@gmail.com), the main contributor of the project for inquiries.

